sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t dietopia/app .
  - docker run dietopia/app rails new . --force --database=postegresql
  - docker ps -a

rvm:
 - 2.5.3
