sudo: required

language: ruby

cache: bundler

services:
  - docker

rvm:
 - 2.5.3

before_install:
  - docker-compose run web rake db:create
  - docker container ls -a
  - docker ps -a
  - docker volume ls

before_script:
  - sudo chmod -R 777 /home/travis/build/derux/dietopia/tmp/

script:
  - bundle exec rake test
  - curl http://localhost:3000
