sudo: required

language: ruby

services:
  - docker

rvm:
 - 2.5.3

before_install:
  - docker build -t dietopia/app .
  - docker run dietopia/app rails new . --force --database=postgresql
  - docker ps -a

script:
  - bundle exec rake test
