sudo: required

language: ruby

cache: bundler

services:
  - docker

rvm:
 - 2.5.3

before_install:
  - docker-compose up -d
  # - docker build -t dietopia/app .
  # - docker run -d dietopia/app bundle exec rails server
  - docker ps -a
  - docker container ls -a
  - docker-compose run web ls -l

before_script:
  - sudo chmod -R 777 /home/travis/build/derux/dietopia/tmp/

script:
  - bundle exec rake test
