sudo: required

language: ruby

cache: bundler

services:
  - docker

rvm:
 - 2.5.3

before_install:
  - docker-compose run web rails new . --force --database=postgresql
  - docker-compose build
  # - docker build -t dietopia/app .
  # - docker run -d dietopia/app bundle exec rails server
  - docker ps -a
  - docker container ls -a
  - docker service ls -a
  - docker-compose run web ls -l

script:
  - bundle exec rake test
