sudo: required

language: ruby

cache: bundler

services:
  - docker

rvm:
 - 2.5.3

before_install:
  - docker build -t dietopia/app .
  - docker run -d dietopia/app bundle exec rails server
  - docker ps -a

script:
  - bundle exec rake test
